blank_issues_enabled: false
contact_links:
  - name: Roblu Discord Server
    url: https://discord.gg/quqRdsthvR
    about: Join the Discord server to chat with developers and other community members!