name: Add Community +1 Comment
on:
  issues:
    types:
      - opened

jobs:
  add-comment:
    runs-on: ubuntu-latest
    permissions: 
      issues: write
    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v1.4.5
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ## Community Note:
            * Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and developers prioritize this request
            * Please do not leave "+1" or other comments that do not add relevant new information or questions
            * If you are interested in working on this issue or have submitted a pull request, please leave a comment
      - name: Add reaction
        uses: aidan-mundy/react-to-issue@v1.0.0
        with:
          issue-number: ${{ github.event.issue.number }}
          reactions: +1
